apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: jfrogauth
      containers:
      - image: orglabel.jfrog.io/default-docker-virtual/demogithubfe:latest
        name: demogithubfe
        resources: {}
        command: 
         - npm
         - run
         - build
        volumeMounts:
          - mountPath: /frontend/build
            name: test-volume
      volumes:
        - name: test-volume
        hostPath:
        # directory location on host
        path: /data
        # this field is optional
        type: Directory
status: {}
